[package]
name = "ander-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pleco = "0.5.0"
chess = "3.2.0"
rand = "0.8.5"
rayon = "1.6.0"